### ISSUE TITLE
Error: Requirements check failed for JDK 1.8 or greater

### ISSUE THREAD

**Issue by sebestenyb** [agileek/docker#10]
Hi

I ran into this error message using the agileek/ionic-framework image.

```
java -version<1s
+ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
ionic info1s
```
```
+ ionic info
Your system information:
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.11
Node Version: v6.10.0
Xcode version: Not installed
```

Can you please upgrade the Java in the image?

Thanks, Sebi

**Comment by MichaelBitard** [comment]
Hi,

I'm working on it now

**Comment by MichaelBitard** [comment]
The image is working on my machine, Docker hub is currently building it here: https://hub.docker.com/r/agileek/ionic-framework/builds/bnbksfpfnmmujfqhulxfgmr/

Once it's done you can use it (Tag: latest and 3.5.0)

I'll let you close this issue if everything works.

**Comment by sebestenyb** [comment]
Thanks heaps!

```
java -version<1s
+ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by kevinky8** [comment]
Para solucionar el problema reinstalar el JDK 1.8 y reiniciar pc

**Comment by abhaygawade** [comment]
Same issue i am facing with oracle jdk 10.0.1 and openk=jdk 10.0.1

java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
