### ISSUE TITLE
Gradle is missing error

### ISSUE THREAD

**Issue by dmastag** [agileek/docker#12]
Hi,

I am running my script like this

```
image: agileek/ionic-framework

variables:
  IONIC_VERSION: "3.9.2"

cache:
  paths:
  - node_modules/
  - platforms/
  - plugins/

before_script:
  - npm install -g ionic@${IONIC_VERSION}

compile_android:
  stage: build
  script:
    - npm install
    - ionic cordova build android --prod
```

But am getting the following error:
```
> cordova build android
✖ Running command - failed!
[ERROR] An error occurred while running cordova build android (exit code 1):

        
        ANDROID_HOME=/opt/android-sdk-linux
        JAVA_HOME=/usr/lib/jvm/java-8-oracle
        Error: Could not find an installed version of Gradle either in Android Studio,
        or on your system to install the gradle wrapper. Please include gradle 
        in your path, or install Android Studio
        
ERROR: Job failed: exit code 1
```

**Comment by dmastag** [comment]
So am trying to install gradle by doing this:
```
before_script:
  - npm install -g ionic@${IONIC_VERSION}
  - apt-get update
  - echo y | apt-get install gradle
```

Hope this one works

**Comment by MichaelBitard** [comment]
I suppose gradle shoud be added in the docker image by default if you can't build an android image without it.
Do you want to create a pull request or I could do it but probably not before wednesday?

**Comment by dmastag** [comment]
Its asking me to use Android Studio to accept a license which I think needs a GUI.
Gotta have to do more research on that

**Comment by dmastag** [comment]
Ok, added the Gradle into #13 
Not sure if that is the right way to do it, kindly review

**Comment by dmastag** [comment]
I also updated the licenses to 25 while I was at it

**Comment by MichaelBitard** [comment]
Thanks, you should be able to test it now, the images are built.
