### ISSUE TITLE
Error when running `ionic platform build android`

### ISSUE THREAD

**Issue by oren** [agileek/docker#2]
`ionic platform build android`

Updated the hooks directory to have execute permissions
running cordova platform add build android
Platform "build" not recognized as a core cordova platform. See `cordova platform list`.

**Comment by oren** [comment]
it works when i change it to `ionic build`

**Comment by MichaelBitard** [comment]
Did you added the android platform before builing it?

```ionic platform add android```

**Comment by oren** [comment]
yup. i'll try reproducing it and report back here. thanks!

**Comment by MichaelBitard** [comment]
Hi,

It seems that the embedded  version in this docker container was too old.

I just released a new version with the latest ionic (1.3.22), everything works for me, can you ```docker pull agileek/ionic-framework``` and try again?

**Comment by oren** [comment]
awesome! i'll do it in a few days and update this issue.

**Comment by oren** [comment]
I am inside the docker container and running: `ionic build android` :

```
[Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.]
ERROR building one of the platforms: Error: /myApp/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /myApp/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

this is not a completely new ionic app so i'll have to try again on new one.

**Comment by oren** [comment]
on a new project i get
```
[Error: Please install Android target: "android-22".

Hint: Open the SDK manager by running: /opt/android-sdk-linux/tools/android
You will require:
1. "SDK Platform" for android-22
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)]
ERROR building one of the platforms: Error: /myApp/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /myApp/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)

```

**Comment by MichaelBitard** [comment]
I am looking into it.

Have you tried to remove the 'platforms' folder inside your application ? I had this issue too but it's not docker-related, it's ionic.

I'm currently updating to the latest ionic version, I'll let you know when it's available.

**Comment by MichaelBitard** [comment]
The latest version is live, and everything works for me (If you migrate from an older ionic project, you will have to do some cleaning before).

I recommend to start from a new project, verify that everything works and then migrate your existing projet.

**Comment by MichaelBitard** [comment]
docker pull agileek/ionic-framework:1.4.5

**Comment by oren** [comment]
everything works now. thanks!

**Comment by MichaelBitard** [comment]
You're welcome!

**Comment by mirfan2017** [comment]
getting this error in cordova 
Error: Platform "android" not recognized as a core cordova platform. See `cordova a platform list`.

![image](https://cloud.githubusercontent.com/assets/26172128/23565034/dc1ddd90-006d-11e7-86bd-b6bd9f9dabe5.png)

**Comment by MichaelBitard** [comment]
@mirfan2017 Can you open a new issue with more details please ?

**Comment by superIvan8** [comment]
Hi MichaelBitard.
How did you solve your problem?

**Comment by MichaelBitard** [comment]
I updated the docker image.

The 2.2.1 is currently building: https://hub.docker.com/r/agileek/ionic-framework/builds/ Once finished you can give it a go
