### ISSUE TITLE
The path /dev/bus/usb is not shared from OS X and is not known to Docker

### ISSUE THREAD

**Issue by TheOnlyMatt** [agileek/docker#28]
Hello ! 
I am very new to docker, so I am not sure of what might be wrong, but I cannot set the automation of the ionic command.

Here is the command I try to get working  : 
`alias ionic="docker run -ti --rm -p 8100:8100 -p 35729:35729 --privileged -v /dev/bus/usb:/dev/bus/usb -v ~/.gradle:/root/.gradle -v /Users/me/my-app-name:/app-name-on-docker:rw agileek/ionic-framework:latest ionic"`

There is no error executing this, but when I run "ionic run android" here is the error I get : 
```
docker: Error response from daemon: Mounts denied: 
The path /dev/bus/usb is not shared from OS X and is not known to Docker.
```

The directory /dev/bus/usb is indeed not existing on my MAC, so I think this is why I don't succeed to get my app running on my physical device.

Can you indicate what should I do to solve this problem ? :)

**Comment by MichaelBitard** [comment]
I'm sorry I don't have a Mac to try it on, I think you should look into stackoverflow for answers on your particular issue, since it's not related to the ionic image.

https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known

Don't hesitate to post your answer here though

**Comment by OKNoah** [comment]
@MichaelBitard That is an unrelated question, it is about. The `/dev` folder deals with devices connected to the machine. It does not seem macOS has a `/dev/bus/usb`, in my research. `/var` is just a folder with files, not nearly as complicated.

**Comment by MichaelBitard** [comment]
I'm sorry, I don't understand what you mean. Feel free to open another issue
