### ISSUE TITLE
agileek/ionic-framework:latest docker image missing version tag

### ISSUE THREAD

**Issue by dschoeni** [agileek/docker#29]
First of all, thanks for the great work with this image. Really helps to build APKs out of Ionic projects.

I noticed that the current agileek/ionic-framework:latest is missing a proper version tag (3.19.1) on Docker Hub (see [here](https://hub.docker.com/r/agileek/ionic-framework/builds/)) - As we use it in our builds, this would be great because we could fix the version and be sure it won't suddenly change. Could you probably push this tag?

**Comment by MichaelBitard** [comment]
You are right, I forgot to tag that :+1: 

The docker image is building: https://hub.docker.com/r/agileek/ionic-framework/builds/bsuhjyyyd3duwc2optvtzjk/

Once it's built and everything works fine, I'll close this PR

Thanks for the issue!
