### ISSUE TITLE
New build with new cordova version

### ISSUE THREAD

**Issue by lukeisontheroad** [agileek/docker#30]
Thanks a lot for this image. Would it be possible to push a new version with the latest cordova version (8.1.2), it would help us as it contains a fix (https://issues.apache.org/jira/browse/CB-13507) we would need for our project.

**Comment by MichaelBitard** [comment]
I'm working on it ;)

**Comment by MichaelBitard** [comment]
I pushed a new version, once it's built (https://hub.docker.com/r/agileek/ionic-framework/builds/blg5q53cb3rtmhno4bf4zkj/) you can try it, and it should work.

agileek/ionic-framework:4.3.1
