### ISSUE TITLE
No device in container

### ISSUE THREAD

**Issue by petruisfan** [agileek/docker#4]
Hello,

I tried running the command:

> docker run -ti --privileged -v /dev/bus/usb:/dev/bus/usb agileek/ionic-framework adb devices

But no device was listed. When running adb devices locally, I see my android phone listed.
Any idea what the problem could be?

**Comment by MichaelBitard** [comment]
Hi,

I'll look into it, it's strange. Is there something under /dev/bus/usb ? 
What is your distribution ?

**Comment by petruisfan** [comment]
I am running ubuntu 14.07
/dev/bus/usb has "001", "002", "003" and "004" folders.
```
$ lsusb                                                                                                                                                                                                     ~/workspace/_other/docker
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 005: ID 04e8:6860 Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II], GT-I9300 Phone [Galaxy S III], GT-P7500 [Galaxy Tab 10.1]
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 13d3:5170 IMC Networks 
Bus 003 Device 004: ID 13ba:0017 PCPlay PS/2 Keyboard+Mouse Adapter
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Thanks!

**Comment by MichaelBitard** [comment]
Have you retried with the latest image ? 

```
docker pull agileek/ionic-framework
```

**Comment by petruisfan** [comment]
Hi Michael,

I think I found out what the problem is.
If I have an adb server running on ubuntu, the docker container doesn't report anything. Probably the device is locked on native or something...
Closing the issue. Thanks for the help!

**Comment by MichaelBitard** [comment]
Thanks for reporting this, I'll add a FAQ to the README

**Comment by petruisfan** [comment]
'adb kill-server' did not do the trick for me.

```
$ docker run -ti --privileged -v /dev/bus/usb:/dev/bus/usb agileek/ionic-framework adb devices # <-- working
$ adb devices # <-- working
$ docker run -ti --privileged -v /dev/bus/usb:/dev/bus/usb agileek/ionic-framework adb devices # <-- not working anymore
$ adb devices # <-- working
$ adb kill-server
$ docker run -ti --privileged -v /dev/bus/usb:/dev/bus/usb agileek/ionic-framework adb devices # <-- still not working anymore
```

I only managed to get docker working again after a restart.

**Comment by MichaelBitard** [comment]
Mmmh, that seems more tricky than I thought, I'll look into it.
Thanks for your feedback

Le lun. 21 sept. 2015 à 10:59, Petru Isfan <notifications@github.com> a
écrit :
