### ISSUE TITLE
ionic build does not work

### ISSUE THREAD

**Issue by akreienbring** [agileek/docker#5]
Hello, i managed running your ionic image (v. 1.4.5) under windows (docker toolbox) with:
```docker run -ti -p 8100:8100 -p 35729:35729 -v //c/Users/<path to existing app>/:/myApp:rw -v //c/Users/<path to .gradle>:/root/.gradle agileek/ionic-framework bash```

ionic -version and ionic prepare seems to be working but ionic build or cordova build does not. The shell writes out
```Running command: /myApp/platforms/android/cordova/build```
and thats it. No more action after that. Can somebody advise me how to solve this?

**Comment by MichaelBitard** [comment]
I dont have a windows machine, it will be difficult to help you.

Have you tried a docker image which contains only cordova? If this kind of image works, we could assume that this is an issue with this particular image or with ionic

You can try with this image for example: https://hub.docker.com/r/webratio/cordova/

**Comment by akreienbring** [comment]
Just tried that. Can't get that image running. I will close this and return to a native installation of ionic as docker on windows seems to have some issues. Too many freezes and non responding shells. 
E.g. in your image, if I go to the android sdk tool and type
```android list sdk``` 
this should list available packages... but simply makes the shell unresponsive... :-(

**Comment by MichaelBitard** [comment]
Sorry to hear that. Windows has still some work to be done in order for
docker to run smoothly

**Comment by pengkobe** [comment]
still not work?
