### ISSUE TITLE
I liked the option to overload a server (/cpus n) - is it still available somehow?

### ISSUE THREAD

**Issue by freiit** [agileek/docker#6]

**Comment by MichaelBitard** [comment]
Yes: https://patrickmn.com/projects/cpuburn/

You can use 
` docker run -it --rm --cpuset-cpus=0,1 agileek/cpuset-test ./cpuburn -n 2`

Sorry, I thought this option was not used.

**Comment by freiit** [comment]
Thanx :) Your container is basis for my stress tests. ;)
Hope one day you introduce a tag, so I don't mind if you change the interface.

**Comment by MichaelBitard** [comment]
You're right, I'll do it

**Comment by MichaelBitard** [comment]
Ok done.

If you want to use the previous version -> agileek/cpuset-test:legacy

**Comment by freiit** [comment]
Thanx :)
