### ISSUE TITLE
Building an android project hangs

### ISSUE THREAD

**Issue by willm** [agileek/docker#7]
Hi, I'm trying to use this image to build an ionic android project, but it seems like `ionic build` just hangs indefinitely. After some digging, I've found that the problem lies in `cordova/bulid`, specifically when it tries to call `android list targets --compact` I know this might be a cordova or even an android issue, however, the same project builds correctly out of docker. I also find the same issue with the default ionic project.

to reproduce:

```
docker run -ti -p 8100:8100 --net host -p 35729:35729 --privileged -v /dev/bus/usb:/dev/bus/usb -v ~/.gradle:/root/.gradle agileek/ionic-framework bash
ionic platform android
ionic build
```

I'm running ubuntu if it makes a difference

**Comment by MichaelBitard** [comment]
Hi,

I can't reproduce this on my computer, I'll try using a different computer

**Comment by willm** [comment]
It seems like this is an issue with my set up as I tried it on our build server and it worked fine. Sorry for bothering you.

**Comment by MichaelBitard** [comment]
No problem!
