### ISSUE TITLE
Container exits when used with docker-compose

### ISSUE THREAD

**Issue by thimmaiah** [agileek/docker#8]
# Problem: The container comes up and then immediately exits.

See output and docker-compose.yml below
## docker-compose up

Creating docker_client_1
Attaching to docker_client_1
client_1  | Running live reload server: undefined
client_1  | Watching: 0=www/**/*, 1=!www/lib/**/*
client_1  | Running dev server:  http://0.0.0.0:8100
client_1  | Ionic server commands, enter:
client_1  |   restart or r to restart the client app from the root
client_1  |   goto or g and a url to have the app navigate to the given url
client_1  |   consolelogs or c to enable/disable console log output
client_1  |   serverlogs or s to enable/disable server log output
client_1  |   quit or q to shutdown the server and exit
client_1  | 
client_1  | ionic $ docker_client_1 exited with code 0
## docker-compose.yml

version: '2'
services:

  client:
    image: agileek/ionic-framework
    volumes:
     - ~/work/angular/firebase-social-login:/myApp:rw
    ports:
     - 8100:8100
     - 35729:35729
    command: ionic serve --all

**Comment by locnguyen** [comment]
Has anyone found a way around this? I tried to add `tty: true` but that only delays the exiting.

**Comment by MichaelBitard** [comment]
Have you tried with `stdin_open: true, tty: true` ? 

This image was not created with docker-compose in mind, so it's possible that there will be issues, see http://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose

the command ionic serve --all expect some input, but docker-compose doesn't allow user interactions
